services:
  nginx: 
    image: nginx
    container_name: kokovet_vite
    ports: 
      - 422:80
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
    restart: unless-stopped
